---
- name: create (download) directory
  file:
    path: "/var/lib/ansible/adminer/downloads"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [configuration, adminer, adminer-download]

- name: download (latest)
  get_url:
    url: "http://www.adminer.org/latest.php"
    dest: "/var/lib/ansible/adminer/downloads/latest.php"
    owner: root
    group: root
    mode: 0644
    force: true
  tags: [configuration, adminer, adminer-download]

- name: install
  file:
    src: "/var/lib/ansible/adminer/downloads/latest.php"
    dest: "{{ adminer.directory }}/adminer.php"
    state: link
    force: true
  with_items: adminer_install_dirs
  tags: [configuration, adminer, adminer-install]
