---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: mysql | Install MySQL Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: mysql | Update root password for all root accounts
  mysql_user: name=root host={{ item }}
              check_implicit_admin=yes
              password={{ mysql.root_password }}
              login_user=root
              login_password={{ mysql.root_password }}
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost
- name: Copy my.cnf global MySQL configuration.
  template:
    src: my.cnf.v1
    dest: "/etc/mysql/my.cnf"
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

# In order to change the innodb log file size, we need to rename the existing ones.
- name: Move the existing logfiles
  shell:  for j in ib_logfile*; do mv -v -- "$j" "$j.bak"; done
  args:
    chdir: /var/lib/mysql/
    removes: ib_logfile0

- name: mysql | Create databases
  mysql_db: name={{ mysql.database }} state=present login_user=root login_password={{ mysql.root_password }}

- name: mysql | Create users
  mysql_user: name={{ mysql.user }} password={{ mysql.password }} priv={{ mysql.database }}.*:ALL state=present login_user=root login_password={{ mysql.root_password }}
