---
- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install php5
  sudo: yes
  apt: pkg=php5 state=latest

- name: Install php5-fpm
  sudo: yes
  apt: pkg=php5-fpm state=latest

- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: php.packages
  when: php.packages is defined

- name: Configure PHP with our php.ini file.
  template:
    src: php.ini.v1
    dest: "/etc/php5/apache2/php.ini"
    owner: root
    group: root
    mode: 0644
  notify: restart apache2

- include: pecl.yml
