- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer creates=/usr/local/bin/composer

- name: Include composer vendor binaries in the path.
  lineinfile:
      dest=/home/vagrant/.bashrc
      line='export PATH="/home/vagrant/.composer/vendor/bin:$PATH"'
      owner=vagrant
      state=present
      insertafter=EOF
      create=True
