source 'https://api.berkshelf.com'

cookbook 'apache2', github: 'onehealth-cookbooks/apache2'
cookbook 'php', '~> 1.4.6'
cookbook 'mongodb', '~> 0.16.1'
cookbook 'mysql', '~> 5.3.6'
cookbook 'composer', '~> 1.0.3'